// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZonaRival.Data;

#nullable disable

namespace ZonaRival.Migrations
{
    [DbContext(typeof(ZonaRivalContext))]
    [Migration("20251015042754_AtributoHoraEnPartido")]
    partial class AtributoHoraEnPartido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZonaRival.Models.Cancha", b =>
                {
                    b.Property<int>("CanchaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CanchaId"));

                    b.Property<string>("NombreCancha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CanchaId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("ZonaRival.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<int>("CantidadJugadores")
                        .HasColumnType("int");

                    b.Property<string>("ColorUniforme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RangoEdad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EquipoId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ZonaRival.Models.EquipoCancha", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.HasKey("EquipoId", "CanchaId");

                    b.HasIndex("CanchaId");

                    b.ToTable("EquiposCanchas");
                });

            modelBuilder.Entity("ZonaRival.Models.Partido", b =>
                {
                    b.Property<int>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartidoId"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PartidoId");

                    b.HasIndex("CanchaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("ZonaRival.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.HasIndex("IdEquipo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ZonaRival.Models.ViewModels.EquipoPartido", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("EquipoId", "PartidoId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EquiposPartidos");
                });

            modelBuilder.Entity("ZonaRival.Models.EquipoCancha", b =>
                {
                    b.HasOne("ZonaRival.Models.Cancha", "Cancha")
                        .WithMany("EquiposCanchas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaRival.Models.Equipo", "Equipo")
                        .WithMany("EquiposCanchas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ZonaRival.Models.Partido", b =>
                {
                    b.HasOne("ZonaRival.Models.Cancha", "Cancha")
                        .WithMany("partidos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ZonaRival.Models.Usuario", b =>
                {
                    b.HasOne("ZonaRival.Models.Equipo", "Equipo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ZonaRival.Models.ViewModels.EquipoPartido", b =>
                {
                    b.HasOne("ZonaRival.Models.Equipo", "Equipo")
                        .WithMany("equipoPartidos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaRival.Models.Partido", "Partido")
                        .WithMany("equipoPartidos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("ZonaRival.Models.Cancha", b =>
                {
                    b.Navigation("EquiposCanchas");

                    b.Navigation("partidos");
                });

            modelBuilder.Entity("ZonaRival.Models.Equipo", b =>
                {
                    b.Navigation("EquiposCanchas");

                    b.Navigation("Usuarios");

                    b.Navigation("equipoPartidos");
                });

            modelBuilder.Entity("ZonaRival.Models.Partido", b =>
                {
                    b.Navigation("equipoPartidos");
                });
#pragma warning restore 612, 618
        }
    }
}
